var PRELOAD_MANIFEST = {
    "path": "images/",
    "manifest": [
        { "id": "section1-pic01", "src": "section1-pic01.jpg" },
        { "id": "section1-pic02", "src": "section1-pic02.png" },
        { "id": "section1-pic03", "src": "section1-pic03.png" },
        { "id": "section1-pic04", "src": "section1-pic04.png" },
        { "id": "section1-pic05", "src": "section1-pic05.png" },
        { "id": "section1-pic06", "src": "section1-pic06.png" },
        { "id": "section1-pic07", "src": "section1-pic07.png" },
        { "id": "section1-pic08", "src": "section1-pic08.png" },
        { "id": "section1-pic09", "src": "section1-pic09.jpg" },
        { "id": "scene1-text1", "src": "scene1-text1.png" },
        { "id": "scene1-text2", "src": "scene1-text2.png" },
        { "id": "scene1-text3", "src": "scene1-text3.png" },
		{ "id": "next", "src": "next.gif" },

        { "id": "section2-pic01", "src": "section2-pic01.jpg" },
        { "id": "section2-pic02", "src": "section2-pic02.png" },
        { "id": "section2-pic03", "src": "section2-pic03.png" },
        { "id": "section2-pic04", "src": "section2-pic04.png" },
        { "id": "section2-pic05", "src": "section2-pic05.png" },
        { "id": "section2-pic06", "src": "section2-pic06.png" },
        { "id": "section2-pic07", "src": "section2-pic07.png" },
        { "id": "scene2-text1", "src": "scene2-text1.png" },
        { "id": "scene2-text2", "src": "scene2-text2.png" },
        { "id": "scene2-text3", "src": "scene2-text3.png" },
		{ "id": "scene2-text4", "src": "scene2-text4.png" },		

        { "id": "section3-pic01", "src": "section3-pic01.jpg" },
        { "id": "section3-pic02", "src": "section3-pic02.png" },
        { "id": "section3-pic03", "src": "section3-pic03.png" },
        { "id": "section3-pic04", "src": "section3-pic04.png" },
        { "id": "section3-pic05", "src": "section3-pic05.png" },
        { "id": "section3-pic06", "src": "section3-pic06.png" },
        { "id": "section3-pic07", "src": "section3-pic07.png" },
        { "id": "section3-pic08", "src": "section3-pic08.png" },
        { "id": "section3-pic09", "src": "section3-pic09.png" },
        { "id": "section3-pic10", "src": "section3-pic10.png" },
        { "id": "section3-pic11", "src": "section3-pic11.png" },
        { "id": "scene3-text1", "src": "scene3-text1.png" },
        { "id": "scene3-text2", "src": "scene3-text2.png" },
        { "id": "scene3-text3", "src": "scene3-text3.png" },		

        { "id": "section4-pic01", "src": "section4-pic01.jpg" },
        { "id": "section4-pic02", "src": "section4-pic02.png" },
        { "id": "section4-pic03", "src": "section4-pic03.png" },
        { "id": "section4-pic04", "src": "section4-pic04.png" },
        { "id": "section4-pic05", "src": "section4-pic05.png" },
        { "id": "section4-pic06", "src": "section4-pic06.png" },
        { "id": "section4-pic07", "src": "section4-pic07.png" },
        { "id": "section4-pic08", "src": "section4-pic08.png" },
        { "id": "section4-pic09", "src": "section4-pic09.png" },
        { "id": "section4-pic10", "src": "section4-pic10.png" },
        { "id": "section4-pic11", "src": "section4-pic11.png" },
        { "id": "scene4-text1", "src": "scene4-text1.png" },
        { "id": "scene4-text2", "src": "scene4-text2.png" },
        { "id": "scene4-text3", "src": "scene4-text3.png" },
		{ "id": "scene4-text4", "src": "scene4-text4.png" },		

        { "id": "section5-pic01", "src": "section5-pic01.jpg" },
        { "id": "section5-pic02", "src": "section5-pic02.png" },
        { "id": "section5-pic03", "src": "section5-pic03.png" },
        { "id": "section5-pic04", "src": "section5-pic04.png" },
        { "id": "section5-pic05", "src": "section5-pic05.png" },
        { "id": "section5-pic06", "src": "section5-pic06.png" },
        { "id": "section5-pic07", "src": "section5-pic07.png" },
        { "id": "section5-pic08", "src": "section5-pic08.png" },
        { "id": "scene5-text1", "src": "scene5-text1.png" },
        { "id": "scene5-text2", "src": "scene5-text2.png" },
        { "id": "scene5-text3", "src": "scene5-text3.png" }		
    ]
}
